# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Python\定时关机\shutWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import popen

def Quit():
    popen('shutdown -a')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 278)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 211, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("wendi.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 20, 231, 101))
        self.label_2.setStyleSheet("font: 20pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 90, 181, 51))
        self.label_3.setStyleSheet("font: 15pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 140, 371, 21))
        self.label_4.setStyleSheet("font: 16pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(374, 190, 81, 23))
        self.pushButton.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 130, 61, 31))
        self.label_5.setStyleSheet("font: 25pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.hide) # type: ignore
        self.pushButton.clicked.connect(Quit)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cheny的关机小助手"))
        self.label_2.setText(_translate("MainWindow", "关机小助手提醒您："))
        self.label_3.setText(_translate("MainWindow", "您已拖堂30秒"))
        self.label_4.setText(_translate("MainWindow", "秒后将自动关机，若想取消请按下按钮"))
        self.pushButton.setText(_translate("MainWindow", "取消"))
        self.label_5.setText(_translate("MainWindow", "30"))
